# Import numpy 

In [15]:
import numpy as np

# Version check

In [9]:
print(np.__version__)

1.19.4


# speed check

In [3]:
%time

Wall time: 0 ns


In [9]:
a = np.arange(6000000) + 5
a[:1000000]
%time

Wall time: 0 ns


In [13]:
l = [[1,2,3],
    [4,5,6],
    [7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [19]:
l2 = np.asarray([1,3,4])
l2


array([1, 3, 4])

In [20]:
l1 = np.arange(1,10)
l1 = l1.reshape((3,3))
l1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
l1 + 5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

# type

In [28]:
type (l2)

numpy.ndarray

# Create a 1D array

In [11]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Create a boolean array

In [13]:
np.ones((3,4),dtype=bool)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

# Replaceing 

In [15]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9,])
arr = np.arange(10)
out = np.where(arr % 2 ==1, -1, arr)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


# Reshape an array

In [16]:
np.arange(10)
arr = np.arange(10)
arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
l2 = np.arange(3*3*3*2).reshape((3,3,3,2))
l2


array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]],


       [[[18, 19],
         [20, 21],
         [22, 23]],

        [[24, 25],
         [26, 27],
         [28, 29]],

        [[30, 31],
         [32, 33],
         [34, 35]]],


       [[[36, 37],
         [38, 39],
         [40, 41]],

        [[42, 43],
         [44, 45],
         [46, 47]],

        [[48, 49],
         [50, 51],
         [52, 53]]]])

# stack two array vertically

In [18]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# stack two array horizontally

In [19]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
np.hstack([a ,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

# Generate custom sequence 

In [21]:
a = np.array([1,2,3])

np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

# get common items between two arrays

In [24]:
a= np.array([1,2,3,2,3,4,3,4,5,6])
b= np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

# Remove common items between two arrays

In [25]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

# get the position where match the two arrays elements

In [29]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,5,7,4,9,4,9,8])
np.where(a == b)

(array([1, 5, 7], dtype=int64),)

# Extract the numbers between two arrays

In [28]:
a = np.array([2,6,1,9,10,3,27])
a[(a >=5)&(a <=10)]

array([ 6,  9, 10])

# Scalars to work on arrays

In [43]:
def maxx(x,y):
    """Get the maximum of two items"""
    if x >=y:
        return x
    else:
        return y
maxx(1, 5)
pair_max = np.vectorize(maxx , otypes=[float])
a = np.array([5,7,9,8,6,4,5])
b = np.array([6,3,4,8,9,7,1])
pair_max(a,b)

array([6., 7., 9., 8., 9., 7., 5.])

# Swap two columns in 2d array

In [46]:
arr =np.arange(9).reshape(3,3)
arr
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

# Swap two rows in 2d array

In [47]:
arr = np.arange(9).reshape(3,3)
arr
arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

# Reverse the rows of 2d array

In [48]:
arr = np.arange(9).reshape(3,3)
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

# Reverse the column of 2d array

In [49]:
arr = np.arange(9).reshape(3,3)
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

# Arry containing random floats between 5 and 10

In [51]:
arr = np.arange(9).reshape(3,3)
rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)

[[7.8485524  7.86864392 7.10580903]
 [5.96256234 6.34907097 5.92304492]
 [6.51009154 9.34875313 8.85581503]
 [5.85223402 9.89098664 7.12606427]
 [5.5567003  6.41709719 5.83681259]]


# Print only 3 decimal places in array

In [54]:
rand_arr = np.random.random((5,3))
np.set_printoptions(precision=3)
rand_arr[:4]

array([[0.16 , 0.008, 0.801],
       [0.83 , 0.686, 0.615],
       [0.43 , 0.89 , 0.304],
       [0.745, 0.709, 0.817]])

# Suppressing the scientific notation

In [64]:
np.random.seed(100)
rand_arr =np.random.random([3,3])/1e3
rand_arr
np.set_printoptions(suppress=False)
np.set_printoptions(suppress=True)
rand_arr

array([[0.001, 0.   , 0.   ],
       [0.001, 0.   , 0.   ],
       [0.001, 0.001, 0.   ]])

# Limit the number of items in array

In [75]:
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

# Get the top n values from array

In [80]:
np.random.seed(100)
a = np.random.uniform(1,50,20)
np.sort(a)[-5:]

array([40.995, 41.467, 42.394, 44.675, 48.953])

# Compute the row wise count of all values in an array

In [2]:
np.random.seed(100)
arr = np.random.randint(1,11,size=(6,10))
arr
def count_of_all__values_rowwise(arr2d):
    num_counts_array = [np.unique(row,return_counts=True) for row in arr2d]
    return([[int(b[a==i])if i in a else 0 for i in np.unique(arr2d)]for a, b in num_count_array])
print(np.arange(1,11)
      counts_of_all_values_rowwise[arr]   


SyntaxError: invalid syntax (<ipython-input-2-7d85d6825f34>, line 8)